# Generated by Django 5.2.4 on 2025-10-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patientbookinginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
