# Generated by Django 5.2.4 on 2025-08-07 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0002_delete_doctorprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('specialization', models.CharField(choices=[('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics')], max_length=50)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qualifications', models.TextField()),
                ('clinic_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('working_days', models.JSONField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('appointment_duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('bio', models.TextField()),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='doctor_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
